version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow_work
    working_dir: /mlflow_work
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow_work/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=./artifacts
    command: >
      mlflow server 
      --host 0.0.0.0 
      --backend-store-uri sqlite:///mlflow_work/mlflow.db 
      --default-artifact-root mlflow-artifacts:/ 
      --serve-artifacts