services:
  mlflow_server:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow_server_energy
    # На macOS порт 5000 часто занят AirPlay (ControlCenter) — используем 5050
    ports:
      - "5050:5000"
    volumes:
      - ./mlflow_data/sqlite:/mlflow/db
      - ./mlflow_data/artifacts:/mlflow/artifacts
    command: >
      mlflow server 
      --backend-store-uri sqlite:////mlflow/db/mlflow.db 
      --default-artifact-root mlflow-artifacts:/ 
      --host 0.0.0.0
      --serve-artifacts