version: '3.8'

services:
  # Сервис трекинга экспериментов
  mlflow_server:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow_server_energy
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data/sqlite:/mlflow/db
      - ./mlflow_data/artifacts:/mlflow/artifacts
    command: >
      mlflow server 
      --backend-store-uri sqlite:////mlflow/db/mlflow.db 
      --default-artifact-root mlflow-artifacts:/ 
      --host 0.0.0.0
      --serve-artifacts

  energy_api:
    build: .
    container_name: energy_api_service
    depends_on:
      - mlflow_server
    ports:
      - "8080:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    volumes:
      - ./data/models:/app/data/models  # Позволяет обновлять модель без пересборки контейнера
    restart: always