{{- if .Values.mlflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "energy-api.mlflowFullname" . }}
  labels:
    {{- include "energy-api.mlflowLabels" . | nindent 4 }}
spec:
  type: {{ .Values.mlflow.service.type }}
  ports:
    - port: {{ .Values.mlflow.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.mlflow.service.type "NodePort") .Values.mlflow.service.nodePort }}
      nodePort: {{ .Values.mlflow.service.nodePort }}
      {{- end }}
  selector:
    {{- include "energy-api.mlflowSelectorLabels" . | nindent 4 }}
{{- end }}
