name: CI/CD Pipeline

on:
  push:
    branches: [ main, "features/**", "infra/**" ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Run Lint (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build-docker:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install DVC
        run: |
          pip install "dvc[gdrive]"

      - name: Pull data from DVC
        env:
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
        run: |
          # Используем проверенный метод настройки через --local
          dvc remote modify storage --local gdrive_client_id $GDRIVE_CLIENT_ID
          dvc remote modify storage --local gdrive_client_secret $GDRIVE_CLIENT_SECRET
          dvc remote modify storage --local gdrive_refresh_token $GDRIVE_REFRESH_TOKEN
          
          # Тянем данные
          dvc pull

      - name: Debug and Fix Structure
        run: |
          echo "Проверяем наличие модели:"
          ls -R data/
          # На случай, если папка data/models создалась пустой, проверим это
          mkdir -p data/models

      - name: Build Docker image
        run: |
          # Собираем образ. Если Dockerfile в корне, путь -f Dockerfile верный.
          docker build -t energy-api-service:latest -f Dockerfile .